"""
Version of podcast_catcher.

Might be autogenerated in the
future based on the git tag.
"""

VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_PATCH = 0

VERSION = (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)
